export * from '@pages/error/Error'
export * from '@pages/home/home'
export * from '@pages/admin/admin'
export * from '@pages/admin/addArticle/addArticle'
export * from '@pages/home/articleDetail/articleDetail'